# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-20 12:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0006_save'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorie',
            name='colour',
            field=models.CharField(default='Red', max_length=30),
            preserve_default=False,
        ),
    ]
