# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-23 21:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0008_signatures'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Signatures',
            new_name='Signature',
        ),
    ]
