# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-24 06:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0009_auto_20171023_2111'),
    ]

    operations = [
        migrations.AddField(
            model_name='signature',
            name='bio',
            field=models.CharField(default='', max_length=400),
            preserve_default=False,
        ),
    ]
