# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-29 21:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0010_signature_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='likes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='article',
            name='ranking',
            field=models.IntegerField(default=0),
        ),
    ]
