# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-02 10:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0012_auto_20171101_2023'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='sous_titre',
            field=models.CharField(default="Phrase d'accroche par d\xe9faut", max_length=400),
            preserve_default=False,
        ),
    ]
