# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-02 10:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0013_article_sous_titre'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='photo',
            field=models.ImageField(default=b'photos_articles/default.jpg', upload_to=b'photos_articles'),
        ),
    ]
