# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-04 16:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0014_article_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='url',
            field=models.CharField(default=b'/', max_length=500),
        ),
    ]
