# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-03 22:19
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('articles', '0015_article_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=400)),
                ('photo', models.ImageField(default=b'photos_articles/default.jpg', upload_to=b'photos_articles')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name=b'Date de creation')),
                ('ranking', models.FloatField(default=0)),
                ('url', models.CharField(default=b'/', max_length=500)),
                ('administrateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Channel_Ask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name=b'Date de demande')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articles.Article')),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articles.Channel')),
            ],
        ),
        migrations.CreateModel(
            name='Channel_Belong',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name=b'Date de demande')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articles.Article')),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articles.Channel')),
            ],
        ),
    ]
