# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-04 11:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0016_channel_channel_ask_channel_belong'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='channel',
            name='administrateur',
        ),
        migrations.RemoveField(
            model_name='channel_ask',
            name='article',
        ),
        migrations.RemoveField(
            model_name='channel_ask',
            name='channel',
        ),
        migrations.RemoveField(
            model_name='channel_belong',
            name='article',
        ),
        migrations.RemoveField(
            model_name='channel_belong',
            name='channel',
        ),
        migrations.AddField(
            model_name='article',
            name='time_to_read',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='Channel',
        ),
        migrations.DeleteModel(
            name='Channel_Ask',
        ),
        migrations.DeleteModel(
            name='Channel_Belong',
        ),
    ]
